### ISSUE TITLE
Noticed a pip failure during building of the sslyze function

### ISSUE THREAD

**Issue by konklone** [dhs-ncats/lambda_functions#5]
Saw this while building the `sslyze` function:

```
build_sslyze_1      | Collecting googleapis-common-protos<2.0dev,>=1.5.3 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Using cached googleapis-common-protos-1.5.3.tar.gz
build_sslyze_1      |     Complete output from command python setup.py egg_info:
build_sslyze_1      |     Traceback (most recent call last):
build_sslyze_1      |       File "<string>", line 1, in <module>
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 10, in <module>
build_sslyze_1      |         from setuptools.extern.six.moves import filter, filterfalse, map
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/setuptools/extern/__init__.py", line 1, in <module>
build_sslyze_1      |         from pkg_resources.extern import VendorImporter
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3017, in <module>
build_sslyze_1      |         @_call_aside
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
build_sslyze_1      |         f(*args, **kwargs)
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3045, in _initialize_master_working_set
build_sslyze_1      |         dist.activate(replace=False)
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2577, in activate
build_sslyze_1      |         declare_namespace(pkg)
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2151, in declare_namespace
build_sslyze_1      |         _handle_ns(packageName, path_item)
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2091, in _handle_ns
build_sslyze_1      |         _rebuild_mod_path(path, packageName, module)
build_sslyze_1      |       File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2120, in _rebuild_mod_path
build_sslyze_1      |         orig_path.sort(key=position_in_sys_path)
build_sslyze_1      |     AttributeError: '_NamespacePath' object has no attribute 'sort'
build_sslyze_1      |     
build_sslyze_1      |     ----------------------------------------
build_sslyze_1      | Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rtbugj3u/googleapis-common-protos/
```

This library isn't used by the `sslyze` scanner, and I think is only used for gathering, so no big deal. But figured I'd flag it.

**Comment by jsf9k** [comment]
I'm not seeing this at all:
```
$ docker-compose up build_sslyze 
Creating network "lambdafunctions_default" with the default driver
Creating lambdafunctions_build_sslyze_1 ... done
Attaching to lambdafunctions_build_sslyze_1
build_sslyze_1      | Collecting pip
build_sslyze_1      |   Downloading pip-9.0.3-py2.py3-none-any.whl (1.4MB)
build_sslyze_1      | Collecting setuptools
build_sslyze_1      |   Downloading setuptools-39.0.1-py2.py3-none-any.whl (569kB)
build_sslyze_1      | Installing collected packages: pip, setuptools
build_sslyze_1      |   Found existing installation: pip 9.0.1
build_sslyze_1      |     Uninstalling pip-9.0.1:
build_sslyze_1      |       Successfully uninstalled pip-9.0.1
build_sslyze_1      |   Found existing installation: setuptools 28.8.0
build_sslyze_1      |     Uninstalling setuptools-28.8.0:
build_sslyze_1      |       Successfully uninstalled setuptools-28.8.0
build_sslyze_1      | Successfully installed pip-9.0.3 setuptools-39.0.1
build_sslyze_1      | Cloning into 'domain-scan'...
build_sslyze_1      | Collecting strict-rfc3339 (from -r domain-scan/requirements.txt (line 8))
build_sslyze_1      |   Downloading strict-rfc3339-0.7.tar.gz
build_sslyze_1      | Collecting publicsuffix (from -r domain-scan/requirements.txt (line 9))
build_sslyze_1      |   Downloading publicsuffix-1.1.0.tar.gz (61kB)
build_sslyze_1      | Collecting boto3 (from -r domain-scan/requirements.txt (line 16))
build_sslyze_1      |   Downloading boto3-1.6.16-py2.py3-none-any.whl (128kB)
build_sslyze_1      | Collecting ipython (from -r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading ipython-6.2.1-py3-none-any.whl (745kB)
build_sslyze_1      | Collecting pshtt from git+git://github.com/dhs-ncats/pshtt.git#egg=pshtt (from -r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Cloning git://github.com/dhs-ncats/pshtt.git to /tmp/pip-build-0j4aumr6/pshtt
build_sslyze_1      | Collecting sslyze<1.4.0,>=1.3.4 (from -r domain-scan/requirements.txt (line 28))
build_sslyze_1      |   Downloading SSLyze-1.3.4.tar.gz (1.0MB)
build_sslyze_1      | Collecting cryptography (from -r domain-scan/requirements.txt (line 29))
build_sslyze_1      |   Downloading cryptography-2.2.1-cp34-abi3-manylinux1_x86_64.whl (2.2MB)
build_sslyze_1      | Collecting pyyaml (from -r domain-scan/requirements.txt (line 32))
build_sslyze_1      |   Downloading PyYAML-3.12.tar.gz (253kB)
build_sslyze_1      | Collecting requests (from -r domain-scan/requirements.txt (line 33))
build_sslyze_1      |   Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
build_sslyze_1      | Collecting google-cloud-bigquery (from -r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading google_cloud_bigquery-0.31.0-py2.py3-none-any.whl (68kB)
build_sslyze_1      | Collecting google-auth-oauthlib (from -r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading google_auth_oauthlib-0.2.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting pytest (from -r domain-scan/requirements.txt (line 49))
build_sslyze_1      |   Downloading pytest-3.5.0-py2.py3-none-any.whl (194kB)
build_sslyze_1      | Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in /var/runtime (from boto3->-r domain-scan/requirements.txt (line 16))
build_sslyze_1      | Collecting botocore<1.10.0,>=1.9.16 (from boto3->-r domain-scan/requirements.txt (line 16))
build_sslyze_1      |   Downloading botocore-1.9.16-py2.py3-none-any.whl (4.1MB)
build_sslyze_1      | Collecting s3transfer<0.2.0,>=0.1.10 (from boto3->-r domain-scan/requirements.txt (line 16))
build_sslyze_1      |   Downloading s3transfer-0.1.13-py2.py3-none-any.whl (59kB)
build_sslyze_1      | Requirement already up-to-date: setuptools>=18.5 in /venv/lib/python3.6/site-packages (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      | Collecting simplegeneric>0.8 (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading simplegeneric-0.8.1.zip
build_sslyze_1      | Collecting pygments (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
build_sslyze_1      | Collecting pickleshare (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading pickleshare-0.7.4-py2.py3-none-any.whl
build_sslyze_1      | Collecting prompt-toolkit<2.0.0,>=1.0.4 (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading prompt_toolkit-1.0.15-py3-none-any.whl (247kB)
build_sslyze_1      | Collecting decorator (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading decorator-4.2.1-py2.py3-none-any.whl
build_sslyze_1      | Collecting pexpect; sys_platform != "win32" (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading pexpect-4.4.0-py2.py3-none-any.whl (56kB)
build_sslyze_1      | Collecting traitlets>=4.2 (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading traitlets-4.3.2-py2.py3-none-any.whl (74kB)
build_sslyze_1      | Collecting jedi>=0.10 (from ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading jedi-0.11.1-py2.py3-none-any.whl (250kB)
build_sslyze_1      | Collecting wget>=3.2 (from pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading wget-3.2.zip
build_sslyze_1      | Collecting docopt (from pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading docopt-0.6.2.tar.gz
build_sslyze_1      | Collecting pytablereader (from pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading pytablereader-0.15.0-py2.py3-none-any.whl (43kB)
build_sslyze_1      | Collecting pytablewriter (from pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading pytablewriter-0.27.2-py2.py3-none-any.whl (52kB)
build_sslyze_1      | Collecting pyopenssl>=17.2.0 (from pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB)
build_sslyze_1      | Collecting nassl<1.1.0,>=1.0.0 (from sslyze<1.4.0,>=1.3.4->-r domain-scan/requirements.txt (line 28))
build_sslyze_1      |   Downloading nassl-1.0.3-cp36-cp36m-manylinux1_x86_64.whl (2.9MB)
build_sslyze_1      | Collecting tls-parser<1.3.0,>=1.2.0 (from sslyze<1.4.0,>=1.3.4->-r domain-scan/requirements.txt (line 28))
build_sslyze_1      |   Downloading tls_parser-1.2.1.tar.gz
build_sslyze_1      | Collecting cffi>=1.7; platform_python_implementation != "PyPy" (from cryptography->-r domain-scan/requirements.txt (line 29))
build_sslyze_1      |   Downloading cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl (421kB)
build_sslyze_1      | Collecting idna>=2.1 (from cryptography->-r domain-scan/requirements.txt (line 29))
build_sslyze_1      |   Downloading idna-2.6-py2.py3-none-any.whl (56kB)
build_sslyze_1      | Requirement already up-to-date: six>=1.4.1 in /var/runtime (from cryptography->-r domain-scan/requirements.txt (line 29))
build_sslyze_1      | Collecting asn1crypto>=0.21.0 (from cryptography->-r domain-scan/requirements.txt (line 29))
build_sslyze_1      |   Downloading asn1crypto-0.24.0-py2.py3-none-any.whl (101kB)
build_sslyze_1      | Collecting certifi>=2017.4.17 (from requests->-r domain-scan/requirements.txt (line 33))
build_sslyze_1      |   Downloading certifi-2018.1.18-py2.py3-none-any.whl (151kB)
build_sslyze_1      | Collecting chardet<3.1.0,>=3.0.2 (from requests->-r domain-scan/requirements.txt (line 33))
build_sslyze_1      |   Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
build_sslyze_1      | Collecting urllib3<1.23,>=1.21.1 (from requests->-r domain-scan/requirements.txt (line 33))
build_sslyze_1      |   Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
build_sslyze_1      | Collecting google-api-core<2.0.0dev,>=1.0.0 (from google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading google_api_core-1.1.0-py2.py3-none-any.whl (51kB)
build_sslyze_1      | Collecting google-resumable-media>=0.2.1 (from google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading google_resumable_media-0.3.1-py2.py3-none-any.whl
build_sslyze_1      | Collecting google-cloud-core<0.29dev,>=0.28.0 (from google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading google_cloud_core-0.28.1-py2.py3-none-any.whl
build_sslyze_1      | Collecting requests-oauthlib>=0.7.0 (from google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading requests_oauthlib-0.8.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting google-auth (from google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading google_auth-1.4.1-py2.py3-none-any.whl (65kB)
build_sslyze_1      | Collecting attrs>=17.4.0 (from pytest->-r domain-scan/requirements.txt (line 49))
build_sslyze_1      |   Downloading attrs-17.4.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting py>=1.5.0 (from pytest->-r domain-scan/requirements.txt (line 49))
build_sslyze_1      |   Downloading py-1.5.3-py2.py3-none-any.whl (84kB)
build_sslyze_1      | Collecting pluggy<0.7,>=0.5 (from pytest->-r domain-scan/requirements.txt (line 49))
build_sslyze_1      |   Downloading pluggy-0.6.0.tar.gz
build_sslyze_1      | Collecting more-itertools>=4.0.0 (from pytest->-r domain-scan/requirements.txt (line 49))
build_sslyze_1      |   Downloading more_itertools-4.1.0-py3-none-any.whl (47kB)
build_sslyze_1      | Requirement already up-to-date: docutils>=0.10 in /var/runtime (from botocore<1.10.0,>=1.9.16->boto3->-r domain-scan/requirements.txt (line 16))
build_sslyze_1      | Requirement already up-to-date: python-dateutil<2.7.0,>=2.1 in /var/runtime (from botocore<1.10.0,>=1.9.16->boto3->-r domain-scan/requirements.txt (line 16))
build_sslyze_1      | Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.4->ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading wcwidth-0.1.7-py2.py3-none-any.whl
build_sslyze_1      | Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading ptyprocess-0.5.2-py2.py3-none-any.whl
build_sslyze_1      | Collecting ipython-genutils (from traitlets>=4.2->ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting parso==0.1.1 (from jedi>=0.10->ipython->-r domain-scan/requirements.txt (line 17))
build_sslyze_1      |   Downloading parso-0.1.1-py2.py3-none-any.whl (91kB)
build_sslyze_1      | Collecting logbook (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading Logbook-1.3.0.tar.gz (83kB)
build_sslyze_1      | Collecting mbstrdecoder (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading mbstrdecoder-0.2.3-py2.py3-none-any.whl
build_sslyze_1      | Collecting typepy>=0.0.20 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading typepy-0.0.22-py2.py3-none-any.whl
build_sslyze_1      | Collecting tabledata>=0.0.5 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading tabledata-0.0.5-py2.py3-none-any.whl
build_sslyze_1      | Collecting markdown2>=2.3.4 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading markdown2-2.3.5.zip (161kB)
build_sslyze_1      | Collecting xlrd>=1.1.0 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading xlrd-1.1.0-py2.py3-none-any.whl (108kB)
build_sslyze_1      | Collecting DataProperty>=0.29.1 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading DataProperty-0.30.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting beautifulsoup4>=4.6.0 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading beautifulsoup4-4.6.0-py3-none-any.whl (86kB)
build_sslyze_1      | Collecting pyparsing>=2.2.0 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading pyparsing-2.2.0-py2.py3-none-any.whl (56kB)
build_sslyze_1      | Collecting pathvalidate>=0.16.2 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading pathvalidate-0.16.3-py2.py3-none-any.whl
build_sslyze_1      | Collecting path.py>=10.3.1 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading path.py-11.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting jsonschema>=2.6.0 (from pytablereader->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading jsonschema-2.6.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting XlsxWriter>=1.0.2 (from pytablewriter->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading XlsxWriter-1.0.2-py2.py3-none-any.whl (139kB)
build_sslyze_1      | Collecting xlwt (from pytablewriter->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading xlwt-1.3.0-py2.py3-none-any.whl (99kB)
build_sslyze_1      | Collecting SimpleSQLite>=0.19.0 (from pytablewriter->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading SimpleSQLite-0.20.0-py2.py3-none-any.whl
build_sslyze_1      | Collecting dominate>=2.3.1 (from pytablewriter->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading dominate-2.3.1.tar.gz
build_sslyze_1      | Collecting elasticsearch>=5.4.0 (from pytablewriter->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading elasticsearch-6.2.0-py2.py3-none-any.whl (69kB)
build_sslyze_1      | Collecting toml>=0.9.3 (from pytablewriter->pshtt->-r domain-scan/requirements.txt (line 25))
build_sslyze_1      |   Downloading toml-0.9.4.tar.gz
build_sslyze_1      | Collecting pycparser (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography->-r domain-scan/requirements.txt (line 29))
build_sslyze_1      |   Downloading pycparser-2.18.tar.gz (245kB)
build_sslyze_1      | Collecting protobuf>=3.0.0 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading protobuf-3.5.2.post1-cp36-cp36m-manylinux1_x86_64.whl (6.4MB)
build_sslyze_1      | Collecting pytz (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading pytz-2018.3-py2.py3-none-any.whl (509kB)
build_sslyze_1      | Collecting googleapis-common-protos<2.0dev,>=1.5.3 (from google-api-core<2.0.0dev,>=1.0.0->google-cloud-bigquery->-r domain-scan/requirements.txt (line 41))
build_sslyze_1      |   Downloading googleapis-common-protos-1.5.3.tar.gz
build_sslyze_1      | Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.7.0->google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading oauthlib-2.0.7-py2.py3-none-any.whl (124kB)
build_sslyze_1      | Collecting pyasn1-modules>=0.2.1 (from google-auth->google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading pyasn1_modules-0.2.1-py2.py3-none-any.whl (60kB)
build_sslyze_1      | Collecting rsa>=3.1.4 (from google-auth->google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
build_sslyze_1      | Collecting cachetools>=2.0.0 (from google-auth->google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading cachetools-2.0.1-py2.py3-none-any.whl
build_sslyze_1      | Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth->google-auth-oauthlib->-r domain-scan/requirements.txt (line 42))
build_sslyze_1      |   Downloading pyasn1-0.4.2-py2.py3-none-any.whl (71kB)
build_sslyze_1      | Installing collected packages: strict-rfc3339, publicsuffix, botocore, s3transfer, boto3, simplegeneric, pygments, pickleshare, wcwidth, prompt-toolkit, decorator, ptyprocess, pexpect, ipython-genutils, traitlets, parso, jedi, ipython, certifi, chardet, idna, urllib3, requests, nassl, pycparser, cffi, asn1crypto, cryptography, tls-parser, sslyze, wget, docopt, logbook, mbstrdecoder, pytz, typepy, DataProperty, pathvalidate, tabledata, markdown2, xlrd, beautifulsoup4, pyparsing, path.py, jsonschema, pytablereader, XlsxWriter, xlwt, SimpleSQLite, dominate, elasticsearch, toml, pytablewriter, pyopenssl, pshtt, pyyaml, protobuf, pyasn1, pyasn1-modules, rsa, cachetools, google-auth, googleapis-common-protos, google-api-core, google-resumable-media, google-cloud-core, google-cloud-bigquery, oauthlib, requests-oauthlib, google-auth-oauthlib, attrs, py, pluggy, more-itertools, pytest
build_sslyze_1      |   Running setup.py install for strict-rfc3339: started
build_sslyze_1      |     Running setup.py install for strict-rfc3339: finished with status 'done'
build_sslyze_1      |   Running setup.py install for publicsuffix: started
build_sslyze_1      |     Running setup.py install for publicsuffix: finished with status 'done'
build_sslyze_1      |   Found existing installation: s3transfer 0.1.12
build_sslyze_1      |     Not uninstalling s3transfer at /var/runtime, outside environment /venv
build_sslyze_1      |   Found existing installation: boto3 1.5.8
build_sslyze_1      |     Not uninstalling boto3 at /var/runtime, outside environment /venv
build_sslyze_1      |   Running setup.py install for simplegeneric: started
build_sslyze_1      |     Running setup.py install for simplegeneric: finished with status 'done'
build_sslyze_1      |   Running setup.py install for pycparser: started
build_sslyze_1      |     Running setup.py install for pycparser: finished with status 'done'
build_sslyze_1      |   Running setup.py install for tls-parser: started
build_sslyze_1      |     Running setup.py install for tls-parser: finished with status 'done'
build_sslyze_1      |   Running setup.py install for sslyze: started
build_sslyze_1      |     Running setup.py install for sslyze: finished with status 'done'
build_sslyze_1      |   Running setup.py install for wget: started
build_sslyze_1      |     Running setup.py install for wget: finished with status 'done'
build_sslyze_1      |   Running setup.py install for docopt: started
build_sslyze_1      |     Running setup.py install for docopt: finished with status 'done'
build_sslyze_1      |   Running setup.py install for logbook: started
build_sslyze_1      |     Running setup.py install for logbook: finished with status 'done'
build_sslyze_1      |   Running setup.py install for markdown2: started
build_sslyze_1      |     Running setup.py install for markdown2: finished with status 'done'
build_sslyze_1      |   Running setup.py install for dominate: started
build_sslyze_1      |     Running setup.py install for dominate: finished with status 'done'
build_sslyze_1      |   Running setup.py install for toml: started
build_sslyze_1      |     Running setup.py install for toml: finished with status 'done'
build_sslyze_1      |   Running setup.py install for pshtt: started
build_sslyze_1      |     Running setup.py install for pshtt: finished with status 'done'
build_sslyze_1      |   Running setup.py install for pyyaml: started
build_sslyze_1      |     Running setup.py install for pyyaml: finished with status 'done'
build_sslyze_1      |   Running setup.py install for googleapis-common-protos: started
build_sslyze_1      |     Running setup.py install for googleapis-common-protos: finished with status 'done'
build_sslyze_1      |   Running setup.py install for pluggy: started
build_sslyze_1      |     Running setup.py install for pluggy: finished with status 'done'
build_sslyze_1      | Successfully installed DataProperty-0.30.0 SimpleSQLite-0.20.0 XlsxWriter-1.0.2 asn1crypto-0.24.0 attrs-17.4.0 beautifulsoup4-4.6.0 boto3-1.6.16 botocore-1.9.16 cachetools-2.0.1 certifi-2018.1.18 cffi-1.11.5 chardet-3.0.4 cryptography-2.2.1 decorator-4.2.1 docopt-0.6.2 dominate-2.3.1 elasticsearch-6.2.0 google-api-core-1.1.0 google-auth-1.4.1 google-auth-oauthlib-0.2.0 google-cloud-bigquery-0.31.0 google-cloud-core-0.28.1 google-resumable-media-0.3.1 googleapis-common-protos-1.5.3 idna-2.6 ipython-6.2.1 ipython-genutils-0.2.0 jedi-0.11.1 jsonschema-2.6.0 logbook-1.3.0 markdown2-2.3.5 mbstrdecoder-0.2.3 more-itertools-4.1.0 nassl-1.0.3 oauthlib-2.0.7 parso-0.1.1 path.py-11.0 pathvalidate-0.16.3 pexpect-4.4.0 pickleshare-0.7.4 pluggy-0.6.0 prompt-toolkit-1.0.15 protobuf-3.5.2.post1 pshtt-0.4.0.dev0 ptyprocess-0.5.2 publicsuffix-1.1.0 py-1.5.3 pyasn1-0.4.2 pyasn1-modules-0.2.1 pycparser-2.18 pygments-2.2.0 pyopenssl-17.5.0 pyparsing-2.2.0 pytablereader-0.15.0 pytablewriter-0.27.2 pytest-3.5.0 pytz-2018.3 pyyaml-3.12 requests-2.18.4 requests-oauthlib-0.8.0 rsa-3.4.2 s3transfer-0.1.13 simplegeneric-0.8.1 sslyze-1.3.4 strict-rfc3339-0.7 tabledata-0.0.5 tls-parser-1.2.1 toml-0.9.4 traitlets-4.3.2 typepy-0.0.22 urllib3-1.22 wcwidth-0.1.7 wget-3.2 xlrd-1.1.0 xlwt-1.3.0
build_sslyze_1      | --2018-03-26 11:20:48--  https://publicsuffix.org/list/public_suffix_list.dat
build_sslyze_1      | Resolving publicsuffix.org (publicsuffix.org)... 63.245.213.25
build_sslyze_1      | Connecting to publicsuffix.org (publicsuffix.org)|63.245.213.25|:443... connected.
build_sslyze_1      | HTTP request sent, awaiting response... 200 OK
build_sslyze_1      | Length: 202319 (198K) [text/plain]
build_sslyze_1      | Saving to: ‘/build/public-suffix-list.txt’
build_sslyze_1      | 
build_sslyze_1      |      0K .......... .......... .......... .......... .......... 25%  310K 0s
build_sslyze_1      |     50K .......... .......... .......... .......... .......... 50%  549K 0s
build_sslyze_1      |    100K .......... .......... .......... .......... .......... 75%  629K 0s
build_sslyze_1      |    150K .......... .......... .......... .......... .......   100% 3.05M=0.3s
build_sslyze_1      | 
build_sslyze_1      | 2018-03-26 11:20:49 (569 KB/s) - ‘/build/public-suffix-list.txt’ saved [202319/202319]
build_sslyze_1      | 
lambdafunctions_build_sslyze_1 exited with code 0
```

**Comment by jsf9k** [comment]
By happenstance I saw this very issue when installing a different package via `pip`.  The problem there was that `setuptools` was out of date.  I suspect you just need to do a `git update` since #3 should fix the problem.

Can you try that and let me know the outcome?

**Comment by konklone** [comment]
This isn't an issue for me any more.
